from aiogram.dispatcher.filters.state import StatesGroup, State

class eng_state(StatesGroup):
    full_name = State()
    date_of_birth = State()
    region = State()
    district = State()
    occupation = State()
    gender = State()
    specialization = State()
    position = State()
    experience = State()
    phone_number = State()
    marital_status = State()
    information = State()
    previously_employed = State()
    size_of_uniform = State()
    attending_school = State()
    learning_style = State()
    workplace = State()
    computer_skills = State()
    desired_salary = State()
    close_relative = State()
    uzbek_citizen = State()
    employed = State()
    job_origin = State()
    photo = State()
    language_proficiency = State()
    check_details = State()