from aiogram.dispatcher.filters.state import StatesGroup, State

class rus_state(StatesGroup):
    fio = State()
    date = State()
    viloyat = State()
    tuman = State()
    kasbi = State()
    jinsi = State()
    mutaxasislik = State()
    ishlash_lavozimi = State()
    ish_tajriba = State()
    tele_raqam = State()
    oilaviy_ahvol = State()
    malumot = State
    avval_kompdaishlagan = State()
    mayka = State()
    oqiydi = State()
    talim_shakli = State()
    kim_bolishishlagan = State()
    kompyuterda_nmbiladi = State()
    oylik = State()
    yaqin_odam = State()
    ozbek_fuqorasimi = State()
    ishlaysizmi = State()
    ish_qayerdanbildiz = State()
    rasm = State()
    til_bilish = State()
    tekshirish = State()